---
- name: "Updating apt repo/cache"
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  become: true
  become_method: sudo

- name: "Upgrade all packages"
  apt: upgrade=yes force_apt_get=yes
  become: true
  become_method: sudo
  
- name: "Installing Packages"
  package:
    name:
      - jq
      - pipx
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - ntpdate
      - flameshot
      - exiftool
      - gnome-terminal
      - bloodhound
      - feroxbuster
      - gobuster
      - oscanner
      - redis-tools
      - tnscmd10g
      - wkhtmltopdf
      - proxychains
    state: latest
  become: true
  become_method: sudo

- name: "Create bloodhound directory if it does not exist"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.sliver-client/extensions/chisel"
    state: directory
    mode: '0755'
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
  become: true
  become_method: sudo

- name: "Copy customqueries.json to bloodhound"
  copy:
    src: "files/customqueries.json"
    dest: "{{ ansible_env.HOME }}/.config/bloodhound/customqueries.json"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0755
  become: true
  become_method: sudo
