- name: "Copy ffufrc to config directory"
  copy:
    src: "files/ffufrc"
    dest: "{{ ansible_env.HOME }}/.config/ffuf/ffufrc"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: 0744
  become: true
  become_method: sudo
