---
- name: "Downloading GitHub Repos into opt"
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.location }}"
    force: true
  loop:
    - { repo: "https://github.com/Flangvik/SharpCollection.git", location: "/opt/SharpCollection" }
    - { repo: "https://github.com/danielmiessler/SecLists", location: "/opt/SecLists" }
    - { repo: "https://github.com/l4rRyxz/scripts.git", location: "/opt/scripts" }
    - { repo: "https://github.com/S3cur3Th1sSh1t/PowerSharpPack.git", location: "/opt/PowerSharpPack" }
    - { repo: "https://github.com/tmux-plugins/tmux-logging.git", location: "/opt/tmux-logging" }
    - { repo: "https://github.com/t3l3machus/Villain", location: "/opt/Villain" }
    - { repo: "https://github.com/l4rRyxz/pre-compiles.git", location: "/opt/pre-compiles" }
    - { repo: "https://github.com/TheWover/donut.git", location: "/opt/donut" }
    - { repo: "https://github.com/RedTeamPentesting/pretender.git", location: "/opt/pretender" }
    - { repo: "https://github.com/X0RW3LL/XenSpawn.git", location: "/opt/XenSpawn" }
    - { repo: "https://github.com/riotsecurity/RepCheck.git", location: "/opt/RepCheck" }
    - { repo: "https://github.com/S3cur3Th1sSh1t/WinPwn.git", location: "/opt/WinPwn" }
    - { repo: "https://github.com/xforcered/SQLRecon.git", location: "/opt/SQLRecon-X" }
    - { repo: "https://github.com/l4rRyxz/RustPacker.git", location: "/opt/RustPacker" }
  become: true
  become_method: sudo

- name: "Install Villain"
  shell: |
    cd /opt/Villain
    sudo pip3 install -r requirements.txt
    sudo chmod +x Villain.py

- name: "Make donut"
  shell: |
    cd /opt/donut
    make
  become: true
  become_method: sudo
