---
# downloading and installing kerbrute
- name: "Cloning Kerbrute from github.com"
  git:
    repo: "https://github.com/ropnop/kerbrute.git"
    dest: "/tmp/kerbrute"
- name: "Building Kerbrute from Source Code"
  shell: |
    cd /tmp/kerbrute
    go build
- name: "Moving Kerbrute to bin and changing execute permissions"
  copy:
    src: "/tmp/kerbrute/kerbrute"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    mode: 0750