---
- name: "Install pipx tools"
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'netexec', url: 'git+https://github.com/Pennyw0rth/NetExec' }
      #- { name: 'crackmapexec', url: 'git+https://github.com/mpgn/CrackMapExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }
    - { name: 'updog', url: 'git+https://github.com/sc0tfree/updog.git' }
    - { name: 'AutoRecon', url: 'git+https://github.com/Tib3rius/AutoRecon.git' }
    - { name: 'man-spider', url: 'git+https://github.com/blacklanternsecurity/MANSPIDER' }
    - { name: 'donpapi', url: 'git+https://github.com/login-securite/DonPAPI.git' }
