---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  tasks:
    - name: "Finished the kali-build"
      debug:
        msg: "Installation completed $:^)"
  roles:
    - role: "roles/configure-tmux"
    - role: "roles/install-tools"
