---
- name: "Customizing Kali"
  hosts: localhost
  connection: local
  tasks:
    - name: "Finished the kali-build"
      debug:
        msg: "Installation completed $:^)"
  roles:
    - role: "roles/customize-zshrc"
    - role: "roles/configure-tmux"
    - role: "roles/install-tools"
    - role: "roles/customize-browser"
    - role: "roles/sliver-extensions"
      # - role: gantsign.visual-studio-code
      #users:
      #    - username: "{{ ansible_user_id }}" 
        # visual_studio_code_extensions:
        #   - streetsidesoftware.code-spell-checker
        #   - ms-python.python
        #   - DEVSENSE.phptools-vscode
        #   - snyk-security.snyk-vulnerability-scanner
