---
# tasks file for configure-tmux

- name: "Install Tmux"
  apt:
    name: tmux
    state: "present" # could leave that blank as "present" is the default state for the apt module.
  become: true
  become_method: sudo
- name: "Copying Tmux Config"
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}"
