---
# tasks file for customize-zshrc
- name: "Modify $PATH variable in .zshrc"
  shell: |
    echo "export PATH=~/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:$PATH" >> ~/.zshrc
    echo "export PATH=~/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:$PATH" >> /root/.zshrc
  become: true
  become_method: sudo
