---
# tasks file for customize-zshrc
- name: "Ensure $PATH is correctly modified with ~/.local/bin added for current user"
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "export PATH=~/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:$PATH"
    create: true

- name: "Ensure $PATH is correctly modified with ~/.local/bin added for root"
  ansible.builtin.lineinfile:
    path: "/root/.zshrc"
    line: "export PATH=~/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:$PATH"
    create: true
  become: true
  become_method: sudo
